sim_name=save-load
#------------------PARAMETERS-------------------------#
# mutation rate
# 0.1 0.01
mut_factor=0.01
# mutation range +- (not currently used)
mut_range=2
# speed
speed_factor=0.02
# absolute max value
speed_max=100
# absolute max value
energy_max=1000
birth_dst = 1.5
# how far the kids are from the parents
light_birth_dst = 1.5
# grid limits
grid_max = 50
# 0.2 0.02 
speed_cost= 0.02
# cost of being alive
# 0.002
step_cost = 0.1
# cost of having sensors
# 0.05
sensor_cost = 0.2
# cost of making sensory errors, ratio of prey energy
# 0.02
error_cost = 0.02
# energy input into system
free_energy = 3
sensor_precision = 5
#
# can be energy or MaxEnergy
energy_cost_type=energy
# energy cost in power law
# 0.1 1.01 
energy_cost_factor=1.01
# maximum number of actions per step
# -1 for infinite
max_number_actions=5

#------------------DISPLAY-------------------------#
#Controls whether the RealMap is displayed. (NB: the ShadowMap is never displayed.)
enable.display = true

#Grid limits
grid.max = 50
grid.step = 20
action.types = 10

#Number of threads to use in <code>RealMap.applyChanges()</code>
nb.threads=  16

#Percentage of elements drawn
draw.coarse = 1

#Number of time steps between two image repaints
refresh.image.every = 1

#------------------FILE SAVING-------------------------#
#ontrols whether to save the data about individuals and predation
save = true
# Percentage of individuals/predations saved.
save.coarse = 0.01
#Controls whether to run the shadow model in parallel to the real model.
run.shadowmodel = false
#Controls whether shadow model data is saved.
#save.shadowmodel = false

# This field is the number of time steps during which to save information about
# dead individuals and predation before switching to news files. */
save.every = 5000

#This field is the number of time steps between two backups of the alive individuals and of the sensors
#Backups allow to stop the program then later resume it at the same point.
backup.every = 100000

# -----------------------
# OEE analysis properties
# -----------------------

# number of time steps between two shadow model resets
shadow_model_reset_every=1000
# number of time steps between two saves of the deltas
deltas_saved_every=1000
