
Make tree animation


Setup

```{r}
library(scatterplot3d)
options(rgl.useNULL = TRUE)
library(rgl)
# library(ggplot2)
# library(gganimate)
library(magick)
library(av)
# colorscience
library(schemr)

library(dplyr)
library(plotly)
library(htmlwidgets)
options(plotly.cdn = FALSE)
suppressWarnings({
  Rtsne_available <- requireNamespace("Rtsne", quietly = TRUE)
})
```

Helper functions
```{r}
read_summary_individuals <- function(folder_path) {
  files <- list.files(
    folder_path,
    pattern = "^SummaryIndividuals_\\d+\\.csv$",
    full.names = TRUE
  )
  nums <- as.integer(sub(".*_(\\d+)\\.csv$", "\\1", basename(files)))
  ord  <- order(nums, na.last = TRUE)
  files <- files[ord]

  cat("Found", length(files), "summary-individual files (numeric order):\n")

  data_list <- lapply(files, function(f) {
    df <- read.csv(f, stringsAsFactors = FALSE)
    if ("isLight" %in% names(df)) {
      df <- df %>% dplyr::select(-isLight, -parentIsLight)  # drop non-numeric lamp flags
    }
    df
  })
  out <- dplyr::bind_rows(data_list, .id = "snapshot_id")
  out$snapshot_index <- as.integer(out$snapshot_id)
  out
}

scale01_safe <- function(x) {
  rng <- range(x, na.rm = TRUE)
  if (!is.finite(rng[1]) || diff(rng) == 0) return(rep(0, length(x)))
  (x - rng[1]) / diff(rng)
}
```


Read data
```{r}
data_folder = "../../../Lana/2024_12_29_17_15/OEE-data/"
whole_world = read_summary_individuals(data_folder)
```

Sample and save

```{r}
ratio = 0.004 # 4
total_n = nrow(whole_world)
n = round(ratio*total_n)

sample_vector=c(1:total_n)
# sample elements from the vector (in this example 30 elements sampled without replacement)
the_sample = sample(sample_vector, n, replace=FALSE)
# the vector of randomly selected elements is then used to select rows from the dataframe
world = whole_world[the_sample,]
```

Save 

```{r}
samples_folder = "../../../Lana/2024_12_29_17_15/sampled/"
write.csv(world, paste0(samples_folder, "4pct.csv"))
```


Plot

```{r}
close3d()
plot3d(x= world$created, y=world$pgmDeath, z = world$maxEnergy) 
rglwidget()
```

Pretty plot

Parameters
```{r}
scene = list(camera = list(
           up=list(x=0, y=0, z=1),
           center=list(x=0, y=0, z=0),
           eye=list(x=1.5, y=-0.5, z=0.5)
         ))

# color
feat_cols <- intersect(c("speed", "maxEnergy", "pgmDeath"), names(world))
#feature matrix
X <- as.data.frame(lapply(feat_cols, function(nm) suppressWarnings(as.numeric(world[[nm]]))))
names(X) <- feat_cols

keep_col <- vapply(X, function(v) any(is.finite(v)), logical(1))
X <- X[, keep_col, drop = FALSE]
if (ncol(X) == 0) {
  world$feat_color <- "#9E9E9E"
} else {
  if (ncol(X) == 1) X <- cbind(X, X) #2 dimensions of features

  for (j in seq_len(ncol(X))) {
    v <- X[[j]]
    mu <- mean(v[is.finite(v)], na.rm = TRUE)
    v[!is.finite(v)] <- mu
    X[[j]] <- v
  }
  #normalise
  X[] <- lapply(X, scale01_safe)
  Xmat <- as.matrix(X)

  set.seed(42L)
  if (Rtsne_available) {
    perp <- max(5, min(30, floor(nrow(Xmat)/3)))
    ts <- Rtsne::Rtsne(Xmat, dims = 2, perplexity = perp, check_duplicates = FALSE, verbose = FALSE)
    emb <- ts$Y
  } else {
    pc <- stats::prcomp(Xmat, center = TRUE, scale. = FALSE)
    emb <- pc$x[, 1:2, drop = FALSE]
  }

  #HSL mapping
  e1 <- emb[, 1]; e2 <- emb[, 2]
  h <- 360 * scale01_safe(e1) # 
  s <-  scale01_safe(e2) # 100 *
  world$feat_color <- paste0("hsl(", round(h), ", ", round(100 *s), "%, 50%)")
  hsl_df = data.frame(h,s,rep(0.50,length(s)))
  rgb = hsl_to_rgb(hsl_df)
  world$color_r = round(rgb$r)
  world$color_g = round(rgb$g)
  world$color_b = round(rgb$b)
}
```

Save file with colors

```{r}
samples_folder = "../../../Lana/2024_12_29_17_15/sampled/"
write.csv(world, paste0(samples_folder, "4pct-color.csv"))
```


Plot

```{r}
fig <- plot_ly(
    world,
    x = ~created,
    y = ~pgmDeath,
    z = ~maxEnergy,
    # text = hover_text,
    hoverinfo = "text",
    type = "scatter3d",
    mode = "markers",
    marker = list(
      color = world$feat_color, # when it was hsv
      size  = 2, #dot_sizes,
      opacity = 0.9
    )
  ) %>% 
  layout(title = "3D Scatter plot", scene = scene)

fig
```



Make the list of rotation matrices

```{r}
close3d()
plot3d(x= world$created, y=world$pgmDeath, z = world$maxEnergy,
       xlab = "時代", ylab = "寿命", zlab = "体の大きさ",
       axes = FALSE,
       col = rgb(world$color_r/255,world$color_g/255, world$color_b/255),
       alpha = 0.8
       ) 

grid3d(c("x", "y+", "z"))
# The default angle is roughly theta = 0, phi = -80. Starting from this position:
view3d(0, -80)
um <- par3d()$userMatrix
rglwidget()

```


https://gist.github.com/slowkow/a9907d8fdc2e85ce539ca4015983b893

```{r}
# rotation matrices
rotation_steps = 500
rotations = list(um)
for (i in c(1:rotation_steps-1)){
  mat = rotate3d(um, 2*pi*i/rotation_steps, 0, 0, 1)
  rotations[[i+1]] = mat
}

```
 
 
 from https://www.geeksforgeeks.org/r-language/how-to-create-3d-plots-and-animations-in-r-using-rgl-package/
 https://www.rdocumentation.org/packages/rgl/versions/1.3.18/topics/play3d
 
 delete existing frames if necessary
 
```{r}
unlink("./movie-frames/*")
```


make frames

```{r}
close3d()

# plot slice by slice
t = 0
i =0
max_t = 2000# max(world$created)
step = 100

plot3d(x= world$created, y=world$pgmDeath, z = world$maxEnergy,
      col = "white", alpha=0,
      xlab = "時代", ylab = "寿命", zlab = "体の大きさ",
      axes = FALSE,
) 
grid3d(c("x", "y+", "z"))
par3d(windowRect = c(20, 30, 800, 800))

while (t<max_t) {
  sub_world = subset(world, created>=t & created<(t+step))
  t = t +step
 
  points3d(x= sub_world$created, y=sub_world$pgmDeath, z = sub_world$maxEnergy,
           col = rgb(sub_world$color_r/255,sub_world$color_g/255, sub_world$color_b/255)#,
           #alpha = 0.8
  )
  
  # rotate
  r_id = i%%rotation_steps + 1
  view3d(userMatrix = rotations[[r_id]])
  
  file_name = sprintf("./movie-frames/frame_%04d.png", i)
  snapshot3d(width = 900, height = 900,
           filename =file_name,
           fmt = "png"
           )
   i = i+1
}

# 
# movie3d(spin3d(axis = c(0, 0, 1)), duration = 2,
#         movie = "movie", frames = "movie", dir = "./movie-frames", clean=FALSE
#         type = "gif"
#         )
# rglwidget()
```

To create the movie run:
https://www.r-bloggers.com/2018/10/the-av-package-production-quality-video-in-r/

or 

https://stackoverflow.com/questions/20126812/mac-terminal-create-animated-gif-from-png-files

```{r}
png_files <- sprintf("./movie-frames/frame_%04d.png", 0:(i-1))
av::av_encode_video(png_files, './movie.mp4', framerate = 5)
```

----

Make the list of rotation matrices

```{r}
close3d()
plot3d(x= world$created, y=world$pgmDeath, z = world$maxEnergy,
       xlab = "時代", ylab = "寿命", zlab = "体の大きさ",
       axes = FALSE,
       col = rgb(world$color_r/255,world$color_g/255, world$color_b/255),
       alpha = 0.8
       ) 
# bbox3d(color = c("grey", "black"), alpha = c(0.2,1))
# segments3d(c(0, max(world$created)*1.3), c(0, 0), c(0, 0), color = "black")
# segments3d(c(0,0), c(0, max(world$pgmDeath)*1.3), c(0, 0), color = "black")
# segments3d(c(0,0), c(0, 0), c(0, max(world$maxEnergy)*1.3), color = "black")

grid3d(c("x", "y+", "z"))

# The default angle is roughly theta = 0, phi = -80. Starting from this position:
view3d(0, -80)
um <- par3d()$userMatrix


p3d =  par3d()
rglwidget()

```

save the current orientation

```{r}
theta_0 <- rglToBase(um)$theta
phi_0 <- rglToBase(um)$phi
```

https://gist.github.com/slowkow/a9907d8fdc2e85ce539ca4015983b893

```{r}
# test = par3dinterp(
#     time = (0:2)*5,
#     userMatrix = list(
#       um,
#       # rotate3d(um, pi / 4, 0, 1, 0), 
#       rotate3d(um, pi, 0, 1, 0),
#       rotate3d(um, -2 * pi, 0, 1, 0)
#     ),
#     method = "linear",
#     extrapolate = "constant"
#  )

# test = par3dinterp(userMatrix=list(um,
#                               rotate3d(um, pi/4, 0, 0, 1), 
#                               rotate3d(um, pi/2, 0, 0, 1) 
#                               )
#                    )

# rotation matrices
rotations = list(um)
for (i in c(1:49)){
  mat = rotate3d(um, 2*pi*1/50, 0, 0, 1)
  rotations[[i+1]] = mat
}

```

https://r-graph-gallery.com/package/gganimate.html
animate

```{r}
ggplot(df, aes(x, y)) +
        geom_point() +
        transition_states(z) +
        shadow_mark() +
        labs(title = "Point num: {closest_state}")
```

