---
title: "plot_full_tree"
output: html_document
---

```{r}
# Setup for inline 3D plotting
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(rgl.useNULL = TRUE)
library(rgl)
rgl::setupKnitr()
library(data.table)

base_folder <- "../../simulation"
folder <- "2025_12_12_23_33"
data_dir <- file.path(base_folder, folder)


files <- list.files(data_dir, pattern="^SummaryIndividuals_\\d+\\.csv$", full.names=TRUE)
stopifnot(length(files) > 0)
```

```{r}
nums <- as.numeric(gsub("\\D", "", basename(files)))
ord  <- order(nums)
files <- files[ord]
nums  <- nums[ord]
y_feat <- "maxEnergy"

splits <- lapply(files, fread)
splits <- Filter(function(dt) nrow(dt) > 0, splits)
stopifnot(length(splits) > 0)
world <- rbindlist(splits, use.names = TRUE, fill = TRUE)

# sample
set.seed(42)
sample_size <- 50000
if (nrow(world) > sample_size) {
  world <- world[sample(.N, sample_size)]
}

ggplot(world, aes(x = created, y = .data[[y_feat]])) +
  geom_point(alpha = 0.5, size = 1.5, color = "black") +
  labs(
    title = paste0("Simulation: ", folder, " | Feature: ", y_feat),
    x = "Created",
    y = y_feat
  ) +
  theme_minimal()
  
```





