

## setup

```{r}
library(scatterplot3d)
options(rgl.useNULL = TRUE)
library(rgl)

# replace with your base folder
base_folder = "../../new_data/"
```

## Read agents data for long data

```{r}
folder = "2024_12_29_17_15_load_long" 
# last screenshot
max_t = 75000
# sample size per file
sample_size = 5000


# read the 1st file
fileName = paste(base_folder, folder,"SummaryIndividuals_0.csv",sep="/")
part_world <- read.csv(fileName, stringsAsFactors=F, dec =".")
sample_vector=c(1:nrow(part_world))
the_sample = sample(sample_vector, sample_size, replace=FALSE)
sample_world = part_world[the_sample,]
world = sample_world

time_step = 5000
t = time_step
while(t<max_t){
  # read 1 file, sample from it
  fileName = paste(base_folder, folder,"/SummaryIndividuals_",t, ".csv", sep="")
  part_world <- read.csv(fileName, stringsAsFactors=F, dec =".")
  sample_vector=c(1:nrow(part_world))
  the_sample = sample(sample_vector, sample_size, replace=FALSE)
  sample_world = part_world[the_sample,]
  
  world = rbind(world, sample_world)
  
  t = t + time_step
}







```




```{r}
colors = rgb(world$speed/max(world$speed), world$maxEnergy/max(world$maxEnergy), world$kidEnergy/max(world$kidEnergy))
close3d()
plot3d(x= world$created, y=world$pgmDeath, z = world$maxEnergy, 
      col = colors, main = folder) # xlim=c(0,max(world$created)), 
rglwidget()
```



```{r}
#  Plot number of agents
t = 0
max_t = max(world$created)
step_size = 100
n_agents_t <- data.frame(Ints=integer(), Ints=integer())
colnames(n_agents_t) = c("t", "n")

while (t < max_t) {
  part_world = subset(world, (world$created>=t) & (world$created<t+step_size))
  n_agents_t = rbind(n_agents_t, c(t, length(part_world$created)))
  t = t + step_size
} 

colnames(n_agents_t) = c("t", "n")

plot(n_agents_t, type = "l", main="Number of agents")

```

Compare number of agents and used energy

```{r}
t = 0
max_t = max(world$created)
step_size = 100
energy_sum <- data.frame(Ints=integer(), Ints=integer())
colnames(energy_sum) = c("t", "e")

while (t < max_t) {
  part_world = subset(world, (world$created>=t) & (world$created<t+step_size))
  energy_sum = rbind(energy_sum, c(t, sum(part_world$maxEnergy)))
  t = t + step_size
} 

colnames(energy_sum) = c("t", "e")

plot(energy_sum, type = "l", main="Stored energy")
points(n_agents_t$t, n_agents_t$n*100, type = "l", col="blue")


```


```{r}
plot(x = world$created, y=world$maxEnergy, main = folder)
points(n_agents_t$t, n_agents_t$n/10, type = "l", col="blue")

```

Try to find N the census; then show clusters at >2N
```{r}
# The census between 40000 and 50000 is on average?
part_world = subset(n_agents_t, t>=40000 & t<50000)
census = mean(part_world$n) # ~100 agents... so little!

# clusters 1 and 2 are separated by at least 50000 steps.
```


