---
title: "oee-md"
author: "Lana"
date: "2025_02_15_19_29"
output: html_document
---

# OEE data analysis

## setup

```{r}
library(scatterplot3d)
options(rgl.useNULL = TRUE)
library(rgl)
# this library allows super fast reading of CSV files!
library(data.table)
library(zoo)
library(properties)

# replace with your base folder
base_folder = "/Users/hyoyeon/Desktop/Career/Sony"
```

## Read agents data

```{r}
folder = "2025_02_15_19_29" #"trees/best-2024_11_05_20_37"
fileName = file.path(base_folder, folder,"SummaryIndividuals_0.csv")
whole_world <- read.csv(fileName, stringsAsFactors=F, dec =".")#, header=TRUE)
world = whole_world
```

## Visualization

```{r}
# plot tree

# # display data as is, or extract a subset
# world = subset(world, created >90000 & created < 110000 & maxEnergy>50)

# # random subset
sample_vector=c(1:nrow(whole_world))
# sample elements from the vector (in this example 30 elements sampled without replacement)
the_sample = sample(sample_vector, 50000, replace=FALSE)
# the vector of randomly selected elements is then used to select rows from the dataframe
world = whole_world[the_sample,]

colors = rgb(world$speed/max(world$speed), world$maxEnergy/max(world$maxEnergy), world$kidEnergy/max(world$kidEnergy))
close3d()
plot3d(x= world$created, y=world$pgmDeath, z = world$maxEnergy, 
      col = colors, main = folder) # xlim=c(0,max(world$created)), 
rglwidget()
```

```{r}
old_world = whole_world
```

```{r}

close3d()
plot3d(x= old_world$created, y=old_world$pgmDeath, z = old_world$maxEnergy,
       col = "black")
points3d(x= whole_world$created, y=whole_world$pgmDeath, z = whole_world$maxEnergy,
       col = "red", main = folder, xlim = c(0, max(whole_world$created)))

rglwidget()

```

```{r}
# plot each variable separately
# par(mfrow=c(2,3))
plot(x = world$created, y=world$speed, main = folder)
plot(x = world$created, y=world$lifeSpan, main = folder)
plot(x = world$created, y=world$sensors, main = folder)
plot(x = world$created, y=world$kidEnergy, main = folder)
plot(x = world$created, y=world$maxEnergy, main = folder)
# plot(x = world$created, y=world$hunger, main = folder)
plot(x = world$created, y=world$nkids, main = folder)
plot(x = world$created, y=world$pgmDeath, main = folder)
#plot(x = world$created, y=world$matForKids, main = folder)
```

```{r}
#  Plot number of agents

library(data.table)

populationFileName = file.path(base_folder, folder,"Population.csv")
population <- fread(populationFileName, dec =".")

plot(population, type = "l", main="Number of agents")

```

```{r}
plot(x = world$created, y=world$maxEnergy, main = folder)
points(n_agents_t$t, n_agents_t$n/10, type = "l", col="blue")

```

## PCA

```{r}
# Apply PCA to whole tree, display clusters
# pca should be on independent vars?

pc <- prcomp(world[c("pgmDeath","maxEnergy", "speed", "kidEnergy", "nkids", "sensors", "matForKids")], #"sensors", 
             center = TRUE,
            scale. = TRUE)

library(ggfortify)
summary(pc)
autoplot(pc)
```

```{r}
# Plot principal components
plot(pc$x[,1])
plot(pc$x[,2])
plot(pc$x[,3])
```

```{r}
# Plot PC as tree
close3d()
plot3d(x= world$created, y=pc$x[,2], z = pc$x[,1], col = colors, main = folder)
rglwidget()
```

```{r}
# PCA over time!
t = min(world$created)
max_t = max(world$created)
step_size = 1000
pc1 = c()
pc2 = c()
pc_t <- data.frame(Ints=integer(), Doubles=double(), Doubles=double())
colnames(pc_t) = c("created", "pc1", "pc2")

while (t < max_t) {
  part_world = subset(world, (world$created>=t) & (world$created<t+step_size))
  pc <- prcomp(part_world[c("pgmDeath","maxEnergy", "speed", "kidEnergy", "nkids", "matForKids")], #"sensors", 
             center = TRUE,
            scale. = TRUE)
  
  temp_df = data.frame(part_world$created, pc$x[,1], pc$x[,2])
  colnames(temp_df) = c("created", "pc1", "pc2")
  pc_t = rbind(pc_t, temp_df)
  
  plot(pc$x[,1],pc$x[,2],main=t)
  
  t = t + step_size
} 
```

```{r}
# PCA on whole tree according to one time slice's projection
t = 4000
part_world = subset(world, (world$created>=t) & (world$created<t+step_size))
pc <- prcomp(part_world[c("pgmDeath","maxEnergy", "speed", "kidEnergy", "nkids", "matForKids")], #"sensors", 
           center = TRUE,
          scale. = TRUE)

projected = predict(pc, world[c("pgmDeath","maxEnergy", "speed", "kidEnergy", "nkids", "matForKids")])

plot(projected[,1])
plot(projected[,2])
plot(projected[,3])

```

## Basic clustering

```{r}
plot(pc$x[,1])
th = -0.5
abline(h=-th)
# compare 2 species (clustering should be cleaner)
s1_pc = subset(part_world, pc$x[,1]>=th)
s2_pc = subset(part_world, pc$x[,1]<th)

```

```{r}

for (cid in c(4:8, 10:12)){
  lim = c( min(c(s1_pc[,cid], s2_pc[,cid])), max(c(s1_pc[,cid],s2_pc[,cid])))
  plot(s1_pc[,cid], col = "red", ylim = lim, main = colnames(s1_pc[cid]))
  points(s2_pc[,cid], col = "blue")
}

```

## Analysis of predation data (Deprecated)

```{r}

# folder = "2025_01_06_16_36" 
fileName = file.path(base_folder, folder,"predation.csv")

interactions <- read.csv(fileName, stringsAsFactors=F, dec =".", header=TRUE, row.names=NULL)

l = length(interactions$t) # step in sim and in this are not ok
interactions$int_id = c(1:l)
sub_interactions = interactions
max_t = max(sub_interactions$t)
print(max_t)
```

```{r}
# 	//-1: death by life span; -2: death by too many kids; -3: eaten; -4 mistake; 0 should mean alive
hist(world$deathCause, breaks = c(-4,-3,-2,-1,0))
max_t = max(world$created)

early = subset(world, created<(max_t/2))
late = subset(world, created>=(max_t/2))

hist(early$deathCause, breaks = c(-4,-3,-2,-1,0))
hist(late$deathCause, breaks = c(-4,-3,-2,-1,0))
```

```{r}
hist(interactions$pred_maxEnergy)
hist(interactions$prey_maxEnergy)

big_preys = subset(interactions, interactions$prey_maxEnergy>10)
hist(big_preys$prey_maxEnergy)

```

```{r}
hist(sub_interactions$successful)

early = subset(sub_interactions, t<(max_t/2))
late = subset(sub_interactions, t>=(max_t/2))

hist(early$successful)
hist(late$successful)
```

```{r}
sub_interactions = subset(interactions, t>30000)
```

Histograms ftw

```{r}
success_eat = subset(sub_interactions, successful>0)
fail_eat =  subset(sub_interactions, successful<0)

hist(success_eat$prey_sensors)
hist(success_eat$prey_maxEnergy)
hist(success_eat$prey_nkids)

```

```{r}
sub_success_eat = subset(success_eat, success_eat$prey_maxEnergy>6)

significant_counts = as.data.frame(table(sub_success_eat$pred_id), stringsAsFactors = FALSE)
hist(significant_counts$Freq)

# significant_counts = subset(significant_counts, significant_counts$Freq > 1)
significant_counts$pred_id = as.integer(significant_counts$Var1)
```

```{r}
significant_interactions = subset(sub_success_eat, pred_id %in% significant_counts$pred_id)

pred_percent = c()
time = 0
step_size = 1000
while (time < max_t) {
  sig = subset(significant_interactions, (t > time) & (t <= (time+step_size)))
  all = subset(success_eat, (t > time) & (t <= (time+step_size)))
  pred_percent = c(pred_percent, length(sig$t)/length(all$t))
  
  time = time + step_size
}

# print(length(significant_interactions$t)/length(success_eat$t))

plot(pred_percent*100)

predation = data.frame(pred_percent)
predation$t = seq(min(interactions$t), max_t, by=step_size)
# predation$t = c(0,seq(min(interactions$t), max_t, by=step_size))

```

```{r}
factor = max(world$speed) - min(world$speed)
plot(x = world$created, y=world$speed, main = folder)
points(predation$t, predation$pred_percent*factor + min(world$speed), type = "l", col="red")

factor = max(world$sensors) - min(world$sensors)
plot(x = world$created, y=world$sensors, main = folder)
points(predation$t, predation$pred_percent*factor + min(world$sensors), type = "l", col="red")

factor = max(world$kidEnergy) - min(world$kidEnergy)
plot(x = world$created, y=world$kidEnergy, main = folder)
points(predation$t, predation$pred_percent*factor + min(world$kidEnergy), type = "l", col="red")

factor = max(world$maxEnergy) - min(world$maxEnergy)
plot(x = world$created, y=world$maxEnergy, main = folder)
points(predation$t, predation$pred_percent*factor + min(world$maxEnergy), type = "l", col="red")

factor = max(world$nkids) - min(world$nkids)
plot(x = world$created, y=world$nkids, main = folder)
points(predation$t, predation$pred_percent*factor + min(world$nkids), type = "l", col="red")

factor = max(world$pgmDeath) - min(world$pgmDeath)
plot(x = world$created, y=world$pgmDeath, main = folder)
points(predation$t, predation$pred_percent*factor + min(world$pgmDeath), type = "l", col="red")

factor = max(world$matForKids) - min(world$matForKids)
plot(x = world$created, y=world$matForKids, main = folder)
points(predation$t, predation$pred_percent*factor + min(world$matForKids), type = "l", col="red")


```

```{r}
hist(significant_interactions$pred_maxEnergy)
hist(significant_interactions$prey_maxEnergy)
```

```{r}
plot(significant_interactions$pred_id, significant_interactions$prey_speed)
```

```{r}
# subset
late_interactions = subset(interactions, t>45000 & t<45500)

colors_pred =  rgb(late_interactions$r_pred, late_interactions$g_pred, late_interactions$b_pred, maxColorValue=255)
colors_prey =  rgb(late_interactions$r_prey, late_interactions$g_prey, late_interactions$b_prey, maxColorValue=255)


# plot predators
plot(late_interactions$r_pred, late_interactions$g_pred, col = colors_pred)

plot(late_interactions$g_prey, late_interactions$b_prey, col = colors_prey)

# plot preys as function of predators
plot(late_interactions$r_pred, late_interactions$g_pred, col = colors_prey)

```

Debug saved data

```{r}
folder = "2024_12_28_06_57/28_06_57"   
fileName = file.path(base_folder, folder,"sensors.csv")
sensors <- read.csv(fileName, header=TRUE)

fileName = file.path(base_folder, folder,"snapshot.csv")
snapshot <- read.csv(fileName, header=TRUE)
```

```{r}
plot(snapshot$x, snapshot$y)
```

```{r}
not_light = subset(snapshot, snapshot$isLight == "false")
plot(not_light$pos_x, not_light$pos_y)

```

## Procedure for testing for Tokyo Type 1 Open-Ended Evolution

```{r}
# replace with a run's folder :
folder = file.path(base_folder, "2025_07_07_17_28")

# number of time steps between each save of the deltas
properties_file = file.path(folder, "config.properties")
DELTAS_SAVED_EVERY = as.numeric(properties::read.properties(properties_file, fields = c("deltas_saved_every")))

# folder where to save the plots
PLOT_FOLDER <- file.path(folder, "evolutionary_activity_stats")
# window size of the moving averages (in number of time steps)
AVERAGE_WINDOW_SIZE_IN_TIME_STEPS <- 100000
# window size of the moving averages (in number of deltas)
AVERAGE_WINDOW_SIZE <- AVERAGE_WINDOW_SIZE_IN_TIME_STEPS / DELTAS_SAVED_EVERY
# color of raw data lines when original ("normal") formula is used
NORMAL_RAW_COL <- "#0072B2"
# color of moving average lines when original ("normal") formula is used
NORMAL_AVERAGE_COL <- "black"
# color of raw data lines when alternative formula is used
ALT_RAW_COL <- "#D55E00"
# color of moving average lines when alternative formula is used
ALT_AVERAGE_COL <- "black"
# width of raw data lines
RAW_LWD <- 1
# width of moving average lines
AVERAGE_LWD <- 2

# paths of the deltas files
realMapDeltasFile <- file.path(folder,"RealMapDeltas.csv")
shadowMapDeltasFile <- file.path(folder,"ShadowMapDeltas.csv")


#' Plot a statistic with optional moving average
#'
#' @param data dataframe with one column "t" (time) and another arbitrary column
#' @param ycol string, the name of the column to plot on Y axis
#' @param ylab string, label of the y-axis
#' @param window_size integer, window size for moving average (default = NULL, no average)
plot_statistic <- function(data, ycol, ylab, window_size = AVERAGE_WINDOW_SIZE, deltas_saved_every = DELTAS_SAVED_EVERY) {
  plot(
    data$t,
    data[[ycol]],
    type = "l",
    col = NORMAL_RAW_COL,
    lwd = RAW_LWD,
    xlab = "Time",
    ylab = ylab
  )
  grid()

  # running average
  if (!is.null(window_size) && window_size > 1) {
    ma <- zoo::rollmean(data[[ycol]], k = window_size, fill = NA, align = "center")
    lines(data$t, ma, col = NORMAL_AVERAGE_COL, lwd = AVERAGE_LWD, lty = 1)
  }
}


#' Saves a plot as a PDF file.
#' 
#' @param filename the name of the PDF file to generate (without the extension)
#' @param plot_function the function that creates the plot
save_plot <- function(filename, plot_function) {
  filepath <- file.path(PLOT_FOLDER, paste0(filename, ".pdf"))
  pdf(filepath)
  plot_function()
  grid()
  invisible(dev.off())
  cat("Saved", filepath, "\r\n")
}
```

### Step 1: Compute basic evolutionary activity statistics

```{r}

# load file
deltas <- fread(realMapDeltasFile, dec = ".")

# ------------------------------
# INITIALIZE TEMPORARY VARIABLES
# ------------------------------
# number of lines
nbLines <- nrow(deltas)
# the components' names
components <- setdiff(names(deltas), "t")
# the number of components
nbComponents <- length(components)
# current accumulations of deltas
currDeltasAccumulations <- setNames(rep(0, nbComponents), components)
# current cumulative evolutionary activities (a)
currCumulativeActivities <- numeric(nbComponents)

# -----------------------------------
# INITIALIZE THE RESULT DATA STRUCTURE
# -----------------------------------
# total cumulative activities (A_cum)
totalActivities <- data.table(t = integer(nbLines), totalActivity = numeric(nbLines))

# -----------------------------------------
# LOOP THAT FILLS THE RESULT DATA STRUCTURE
# -----------------------------------------
start_time <- proc.time() # to measure the time that the computation takes
for (line in 1:nbLines) {
  # read the time
  t <- deltas[line, t]
  # print the elapsed computation time since the start of this loop
  if (t %% 100000 == 0) {
    elapsed <- (proc.time() - start_time)[["elapsed"]]
    cat(sprintf("\rt = %d ; elapsed time = %.1f seconds", t, elapsed))
  }
  # compute and store the results
  currDeltas <- as.numeric(deltas[line, ..components])
  currDeltasAccumulations <- currDeltasAccumulations + currDeltas
  currCumulativeActivities <- ifelse(currDeltas == 1, currDeltasAccumulations, 0)
  totalActivities[line, ] <- list(t, sum(currCumulativeActivities))
}

```

```{r}

# ---------------
# PLOT STATISTICS
# ---------------

dir.create(PLOT_FOLDER, showWarnings = FALSE)


# === TOTAL ACTIVITY ===

f <- function() plot_statistic(totalActivities, "totalActivity", "Total activity")
f()
save_plot("total_activity", f)
```

### Step 2: Compute component-normalized evolutionary activity statistics

```{r}

# load files
realDeltas <- fread(realMapDeltasFile, dec = ".")
shadowDeltas <- fread(shadowMapDeltasFile, dec = ".")


# ------------------------------
# INITIALIZE TEMPORARY VARIABLES
# ------------------------------
# the number of lines in each file
nbLines <- nrow(realDeltas)
# the real model's components' names
realComponents <- setdiff(names(realDeltas), "t")
# the shadow model's components' names
shadowComponents <- setdiff(names(shadowDeltas), "t")
# union of real components' names and shadow components' names
allComponents <- union(realComponents, shadowComponents)
# current accumulations of normalized deltas (original formula)
currNormDeltasAccs <- setNames(rep(0, length(allComponents)), allComponents)
# current accumulations of normalized deltas (alternative formula)
altCurrNormDeltasAccs <- setNames(rep(0, length(realComponents)), realComponents)
# indicates which component has already been considered new
hasBeenNew <- setNames(rep(FALSE, length(realComponents)), realComponents)

# -------------------------------------
# INITIALIZE THE RESULT DATA STRUCTURES
# -------------------------------------
# total normalized activities (original formula)
normTotalActivities <- data.table(t = integer(nbLines), normTotalActivity = numeric(nbLines))
# median normalized activities (original formula)
normMedianActivities <- data.table(t = integer(nbLines), normMedianActivity = numeric(nbLines))
# total normalized activities (alternative formula)
altNormTotalActivities <- data.table(t = integer(nbLines), normTotalActivity = numeric(nbLines))
# median normalized activities (alternative formula)
altNormMedianActivities <- data.table(t = integer(nbLines), normMedianActivity = numeric(nbLines))
# new normlized activities
normNewActivities <- data.table(t = integer(nbLines), normNewActivity = numeric(nbLines))

# -----------------------------------------
# LOOP THAT FILLS THE RESULT DATA STRUCTURES
# -----------------------------------------
start_time <- proc.time() # to measure the time the computation takes
for (line in 1:nbLines) {

  # read the time
  t <- realDeltas[line, t]

  # print the elapsed computation time
  if (t %% 10000 == 0) {
    elapsed <- (proc.time() - start_time)[["elapsed"]]
    cat(sprintf("\rt = %d ; elapsed time = %.1f seconds", t, elapsed))
  }

  # names of components that currently exist in the real model
  realActiveComps <- realComponents[which(realDeltas[line, ..realComponents] == 1)]


  # === READ/COMPUTE DELTAS ===
  
  currRealDeltas <- setNames(rep(0, length(allComponents)), allComponents)
  currShadowDeltas <- setNames(rep(0, length(allComponents)), allComponents)
  if (length(realComponents) > 0) {
    currRealDeltas[realComponents] <- as.numeric(realDeltas[line, ..realComponents])
  }
  if (length(shadowComponents) > 0) {
    currShadowDeltas[shadowComponents] <- as.numeric(shadowDeltas[line, ..shadowComponents])
  }
  currNormDeltas <- currRealDeltas - currShadowDeltas
  names(currNormDeltas) <- allComponents


  # === COMPUTE TOTAL AND MEDIAN ACTIVITIES (ORIGINAL FORMULA) ===

  currNormDeltasAccs <- currNormDeltasAccs + currNormDeltas
  currNormCumActivities <- ifelse(currRealDeltas == 1, currNormDeltasAccs, 0)
  normTotalActivities[line] <- list(t, sum(currNormCumActivities[realActiveComps]))
  normMedianActivities[line] <- list(t, if (length(realActiveComps) > 0) median(currNormCumActivities[realActiveComps]) else NA)


  # === COMPUTE TOTAL AND MEDIAN ACTIVITIES (ALTERNATIVE FORMULA) ===

  altCurrNormDeltasAccs[realActiveComps] <- altCurrNormDeltasAccs[realActiveComps] + currNormDeltas[realActiveComps]
  altCurrNormCumActivities <- ifelse(currRealDeltas[realComponents] == 1, altCurrNormDeltasAccs, 0)
  altNormTotalActivities[line]   <- list(t, sum(altCurrNormCumActivities[realActiveComps]))
  altNormMedianActivities[line] <- list(t, if (length(realActiveComps) > 0) median(altCurrNormCumActivities[realActiveComps]) else NA)


  # === COMPUTE NEW ACTIVITIES ===
  
  # compute minimum cumulative activity of the real components
  currNormCumActivitiesOfRealComps <- currNormCumActivities[realComponents]
  minNormCumulativeActivity <- min(currNormCumActivitiesOfRealComps)
  # compute current diversity in the real model
  realDiversity <- sum(currRealDeltas[realComponents])
  # initialize the sum of normalized cumulative activities of new components
  sumOfNormCumActivitiesOfNewComps <- 0
  # determine new components then add their normalized cumulative activities to the previous sum
  if (minNormCumulativeActivity < 0) {
    # threshold beyond which a component is considered adaptively significant
    aN0 <- abs(minNormCumulativeActivity)
    # determine components that are new (or "newly adaptively significant")
    isNewComponent <- currNormCumActivitiesOfRealComps > aN0 & !hasBeenNew[realComponents]
    newComponents <- names(currNormCumActivitiesOfRealComps)[isNewComponent]
    hasBeenNew[newComponents] <- TRUE
    # update the sum
    sumOfNormCumActivitiesOfNewComps <- sum(currNormCumActivitiesOfRealComps[newComponents])
  }
  # compute new activities
  normNewActivities[line] <- list(t, if (realDiversity > 0) sumOfNormCumActivitiesOfNewComps/realDiversity else NA)

}

cat("\n")

```

```{r}

# ---------------
# PLOT STATISTICS
# ---------------

dir.create(PLOT_FOLDER, showWarnings = FALSE)


# === TOTAL NORMALIZED ACTIVITY (ORIGINAL FORMULA) ===

f <- function() plot_statistic(normTotalActivities, "normTotalActivity", "Total normalized activity")
f()
save_plot("total_normalized_activity", f)

# === MEDIAN NORMALIZED ACTIVITY (ORIGINAL FORMULA) ===

f <- function() plot_statistic(normMedianActivities, "normMedianActivity", "Median normalized activity")
f()
save_plot("median_normalized_activity", f)


# === NEW ACTIVITY (ORIGINAL FORMULA) ===

f <- function() plot_statistic(normNewActivities, "normNewActivity", "New activity")
f()
save_plot("new_activity", f)

# === TOTAL NORMALIZED ACTIVITY (ALTERNATIVE FORMULA) ===

f <- function() plot_statistic(altNormTotalActivities, "normTotalActivity", "Total normalized activity")
f()
save_plot("total_normalized_activity_alt", f)

# === MEDIAN NORMALIZED ACTIVITY (ALTERNATIVE FORMULA) ===

f <- function() plot_statistic(altNormMedianActivities, "normMedianActivity", "Median normalized activity")
f()
save_plot("median_normalized_activity_alt", f)

# === NEW ACTIVITY (ALTERNATIVE FORMULA) ===
# TODO

```