sim_name=line by line
# mutation rate
# 0.1 0.01
mut_factor=0.01
# mutation range +- (not currently used)
mut_range=2
# speed
speed_factor=0.02
# absolute max value
speed_max=100
# absolute max value
energy_max=1000
birth_dst = 1.5
# how far the kids are from the parents
light_birth_dst = 1.5
# grid limits
grid_max = 50
# 0.2 0.02 
speed_cost= 0.02
# cost of being alive
# 0.002
step_cost = 0.1
# cost of having sensors
# 0.05
sensor_cost = 0.2
# cost of making sensory errors, ratio of prey energy
# 0.02
error_cost = 0.02
# energy input into system
free_energy = 3
sensor_precision = 5
#
# can be energy or MaxEnergy
energy_cost_type=energy
# energy cost in power law
# 0.1 1.01 
energy_cost_factor=1.01 
# maximum number of actions per step
# -1 for infinite
max_number_actions=5